from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import WebDriverException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import Select

#LINK NA I AUTOMATE AT TEST
driver = webdriver.Chrome()
driver.get("http://p1wwebd08/lmsv2/auth/login")
driver.maximize_window()
element = WebDriverWait(driver, 5).until(
EC.presence_of_element_located((By.ID, "active_directory"))
)
element.click()
#ADMIN USER AT PASSWORD
try:
    username_field = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, "ademployee"))
    )
    password_field = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.NAME, "password"))
    )
    username_field.send_keys("JMOYA")
    password_field.send_keys("Ciana052497!3")

    submit_button = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//button[@type='submit']"))
    )
    submit_button.click()
    time.sleep(3)
#LINK PATH NG COURSE NA I CREATE
    driver.get("http://p1wwebd08/lmsv2/curriculum/home")
    link = driver.find_elements(By.XPATH, "//a[@href]")
    for link in link:
        if "files" in link.get_attribute("innerHTML"):
            driver.execute_script("http://p1wwebd08/lmsv2/curriculum/add")
    submit_button = WebDriverWait(driver, 10).until
    EC.element_to_be_clickable((By.CLASS_NAME, "active"))
    time.sleep(3)
#LINK SA ADD COURSE CODEEEEEEEEEE
    driver.get("http://p1wwebd08/lmsv2/curriculum/add")
#CREATE COURSE CODEEEEEEEEEEEEEEEEE
#TITLE NG COURSE
    driver.find_element(By.NAME, "curriculum_name").click()
    driver.find_element(By.ID, "curriculum_name").send_keys("Test_Curriculum_jmoya")
    time.sleep(3)
#DESCRIPTION NG COURSE
    driver.find_element(By.NAME, "curriculum_description").click()
    driver.find_element(By.ID, "curriculum_description").send_keys("autogenerated on python webdriver")
#TARGET ATTENDEESAYTIZ
    driver.find_element(By.ID, "department").click()
    driver.find_element(By.ID, "department").send_keys("Engineering 1")
    driver.find_element(By.ID, "btnCourseList").click()
    time.sleep(3)
#ADD COURSE
    checkbox_element = driver.find_element(By.XPATH, "//input[@type='checkbox' and @name='check' and @value='9']")
    checkbox_element.click()
    checkbox_element = driver.find_element(By.XPATH, "//input[@type='checkbox' and @name='check' and @value='10']")
    checkbox_element.click()
    time.sleep(3)
    driver.find_element(By.ID, "btnCourseSelect").click()
    time.sleep(3)
#YES OR NO SELECTION CODE
    span_element = driver.find_element(By.XPATH, "//form[@id='frmAdd']/div[6]/div/label[2]/span")
    span_element.click()
    time.sleep(3)
#SUBMIT BUTTON
    driver.find_element(By.ID, "btnAddPreview").click()
    time.sleep(3)
    button_element = driver.find_element(By.ID, "btnAddPreviewSubmit")
    button_element.click()
    time.sleep(3)
finally:
    time.sleep(100)
